[package]
name = "lab_rust_crud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.2"

[dev-dependencies]
hyper = { version = "1.1.0", features = ["client"] }
